apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
spec:
  destination:
    name: ''
    namespace: votingapp
    server: 'https://kubernetes.default.svc'
  source:
    path: Lab-20/voting-app
    repoURL: 'https://github.com/gurretl/labs.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
