version: "3.9"
    
services:
  db:
    image: "{{IMAGE}}"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "{{MYSQL_ROOT_PASSWORD}}"
      MYSQL_DATABASE: "{{MYSQL_DATABASE}}"
      MYSQL_USER: "{{MYSQL_USER}}"
      MYSQL_PASSWORD: "{{MYSQL_PASSWORD}}"
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "{{WORDPRESS_DB_HOST}}"
      WORDPRESS_DB_USER: "{{WORDPRESS_DB_USER}}"
      WORDPRESS_DB_PASSWORD: "{{WORDPRESS_DB_PASSWORD}}"
      WORDPRESS_DB_NAME: "{{WORDPRESS_DB_NAME}}"
volumes:
  db_data: {}

