---
repos:
  - repo: https://github.com/google/yamlfmt
    rev: v0.11.0
    hooks:
      - id: yamlfmt
        args: [-formatter, include_document_start=true]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-no-color
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.17.0
    hooks:
      - id: terraform-docs-system
        args: [--config, .terraform-docs.yml, "--output-file", "doc/README.md", .]
