apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins-k8s.fullname" . }}
  labels:
    app: {{ template "jenkins-k8s.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.adminUser | b64enc | quote }}
{{- if .Values.adminPassword }}
  jenkins-admin-password: {{ .Values.adminPassword | b64enc | quote }}
{{- else }}
  jenkins-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
