# Default values for jenkins-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

initContainerImage: "alpine:3.10.2"

replicaCount: 1
imagePullSecrets:
image:
  repository: lionel/jenkins
  tag: v1
  #pullPolicy: Always
  pullPolicy: Never
did:
  image:
    repository: docker
    tag: 18.09.8-dind
  # Resources for the DIND container
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 2Gi

## Set the admin user
adminUser: admin
## Make sure to replace the default password
adminPassword: P4ssw0rd!
service:
  name: jenkins-k8s
  #type: LoadBalancer
  type: NodePort
  ## Whitelist the IPs that can access Jenkins
  #loadBalancerSourceRanges:
  #- 0.0.0.0/0
  nodePort: 31000
  externalPort: 8080
  internalPort: 8080
## Make sure the javaOps and resources are aligned to avoid conflicts
javaOpts: "-Xms512m -Xmx2g"
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 3Gi
storage:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
  capacity: 50Gi
