apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat
  name: tomcat-service
  namespace: jenkins
spec:
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat
  type: NodePort
