apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
  name: tomcat-deployment
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      volumes:
        - name: tomcat-home
          persistentVolumeClaim:
            claimName: tomcat-pv-claim
      containers:
      - image: saravak/tomcat8
        name: tomcat8
        volumeMounts:
          - name: tomcat-home
            mountPath: /opt/tomcat
  replicas: 1
