apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
  - image: debian:latest
    name: container-1
    command: ['/bin/bash', '-c', 'sleep 10000']
    volumeMounts:
    - mountPath: /tmp/container-1-dir
      name: volume-share
  - image: debian:latest
    name: container-2
    command: ['/bin/bash', '-c', 'sleep 10000']
    volumeMounts:
    - mountPath: /tmp/container-2-dir
      name: volume-share
  volumes:
  - name: volume-share
    emptyDir: {}

